# Generated by Django 6.0.1 on 2026-02-11 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(auto_now_add=True, verbose_name='Assigned At')),
                ('registration_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('Manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField(max_length=4)),
                ('chassis_number', models.CharField(max_length=30)),
                ('engine_number', models.CharField(max_length=30)),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('IU', 'In Use'), ('MA', 'Maintenance')], default='AV', max_length=2)),
                ('ownership_type', models.CharField(choices=[('CO', 'Company Owned'), ('VL', 'Vendor Lease'), ('DO', 'Driver Owned')], default='CO', max_length=2)),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='Vehicle Image')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_provider', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40, verbose_name='Service Type')),
                ('description', models.TextField()),
                ('mileage_at_service', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Service Date')),
                ('next_service_due', models.DateField(null=True, verbose_name='Next Service Due')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Driver')),
            ],
        ),
    ]
