# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="average_mpg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Average MPG (for IFTA)",
            ),
        ),
        migrations.CreateModel(
            name="IFTAMileageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.IntegerField(choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6"), (7, "7"), (8, "8"), (9, "9"), (10, "10"), (11, "11"), (12, "12")])),
                ("year", models.IntegerField()),
                ("state_code", models.CharField(max_length=2)),
                ("miles_driven", models.DecimalField(decimal_places=2, max_digits=12)),
                ("calculated_gallons", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("truck", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle", verbose_name="Truck")),
            ],
            options={
                "verbose_name": "IFTA Mileage Log",
                "verbose_name_plural": "IFTA Mileage Logs",
                "ordering": ["-year", "-month", "state_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="iftamileagelog",
            constraint=models.UniqueConstraint(fields=("truck", "month", "year", "state_code"), name="vehicles_iftamileagelog_unique_truck_month_year_state"),
        ),
    ]
