# Generated by Django 6.0.1 on 2026-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_iftamileagelog_vehicles_iftamileagelog_unique_truck_month_year_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
