# Generated by Django 6.0.1 on 2026-03-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='next_service_mileage',
            field=models.IntegerField(blank=True, help_text='Mileage at which the next service should occur.', null=True, verbose_name='Next Service Mileage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(blank=True, help_text='Most recent odometer reading (miles).', null=True, verbose_name='Current Odometer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gomotive_id',
            field=models.CharField(blank=True, help_text='If set, mileage and maintenance can be synced from GoMotive.', max_length=64, null=True, verbose_name='GoMotive Vehicle ID'),
        ),
        migrations.CreateModel(
            name='IFTAMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2, verbose_name='State')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')], verbose_name='Quarter')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('miles', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miles Driven')),
                ('calculated_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Computed Gallons (from MPG)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_mileage_entries', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'IFTA Mileage Entry',
                'verbose_name_plural': 'IFTA Mileage Entries',
                'ordering': ['-year', '-quarter', 'state_code'],
                'unique_together': {('vehicle', 'state_code', 'quarter', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='IFTAMileageLog',
        ),
    ]
