# Generated by Django 6.0.1 on 2026-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_maintenance_next_service_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='gomotive_alert_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='GoMotive Alert ID'),
        ),
    ]
