# Generated by Django 6.0.1 on 2026-04-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_joined_at_driver_joined'),
        ('vehicles', '0006_maintenance_gomotive_alert_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iftamileage',
            options={'ordering': ['-year', '-month', 'state_code'], 'verbose_name': 'IFTA Entry', 'verbose_name_plural': 'IFTA Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='iftamileage',
            unique_together={('vehicle', 'state_code', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='iftamileage',
            name='gallons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gallons Consumed'),
        ),
        migrations.AddField(
            model_name='iftamileage',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='iftamileage',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miles Driven'),
        ),
        migrations.AlterField(
            model_name='iftamileage',
            name='state_code',
            field=models.CharField(default='IL', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(max_length=30, verbose_name='VIN (Chassis Number)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/', verbose_name='Vehicle Image'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.RemoveField(
            model_name='iftamileage',
            name='calculated_gallons',
        ),
        migrations.RemoveField(
            model_name='iftamileage',
            name='quarter',
        ),
    ]
