# Generated by Django 6.0.1 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_iftamileage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='mileage_at_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_service_due',
            field=models.DateField(blank=True, null=True, verbose_name='Next Service Due'),
        ),
    ]
