# Generated by Django 6.0.1 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_maintenance_mileage_at_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Service Type'),
        ),
    ]
