# Generated by Django 6.0.1 on 2026-05-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iftamileage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_mileage_entries', to='vehicles.vehicle', verbose_name='Truck Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20, verbose_name='Truck Number'),
        ),
    ]
