# Generated by Django 6.0.1 on 2026-02-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
