# Generated by Django 6.0.1 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_options_driver_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='driver',
            name='joined',
            field=models.DateField(blank=True, null=True, verbose_name='Date Joined'),
        ),
    ]
