# Generated by Django 6.0.1 on 2026-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default per-shipment rate for this customer (can be overridden per shipment).', max_digits=10, null=True, verbose_name='Default Rate ($)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='abbreviation',
            field=models.CharField(max_length=20, verbose_name='Abbreviation / Short Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
