# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_date", models.DateField()),
                ("status", models.CharField(choices=[("Draft", "Draft"), ("Sent", "Sent"), ("Paid", "Paid")], default="Draft", max_length=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="customers.customer")),
            ],
            options={
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_incurred", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("container_no", models.CharField(blank=True, max_length=50, null=True)),
                ("seal_no", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="shipments.invoice")),
                ("shipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="shipments.shipment")),
            ],
            options={
                "ordering": ["date_incurred", "id"],
            },
        ),
    ]
