# Generated by Django 6.0.1 on 2026-03-06 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_default_rate_and_more'),
        ('drivers', '0003_alter_driver_options_driver_status_and_more'),
        ('shipments', '0002_invoice_invoicelineitem'),
        ('vehicles', '0004_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('invoiced', 'Invoiced')], default='pending_review', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rate ($)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='booking',
            field=models.CharField(max_length=50, verbose_name='Booking #'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='container',
            field=models.CharField(max_length=50, verbose_name='Container #'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(verbose_name='Shipment Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seal',
            field=models.CharField(max_length=50, verbose_name='Seal #'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Vehicle'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('category', models.CharField(choices=[('driver_pay', 'Driver Pay'), ('repairs', 'Repairs / Maintenance Parts'), ('insurance', 'Insurance'), ('fuel', 'Fuel'), ('tolls', 'Tolls'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount ($)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Receipt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IFTARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2, verbose_name='State Code')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='Quarter')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Tax Rate ($/gallon)')),
            ],
            options={
                'verbose_name': 'IFTA Rate',
                'verbose_name_plural': 'IFTA Rates',
                'ordering': ['-year', '-quarter', 'state_code'],
                'unique_together': {('state_code', 'quarter', 'year')},
            },
        ),
    ]
