# Generated by Django 6.0.1 on 2026-03-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_options_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Flagged (Issue)'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Raw Message Text')),
                ('sender_phone', models.CharField(blank=True, max_length=50, verbose_name='Sender Phone')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
