# Generated by Django 6.0.1 on 2026-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_is_flagged_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidecar_status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20, verbose_name='Sidecar Status')),
                ('auth_status', models.CharField(choices=[('not_authenticated', 'Not Authenticated'), ('authenticating', 'Authenticating (Scan QR)'), ('authenticated', 'Authenticated')], default='not_authenticated', max_length=20, verbose_name='Auth Status')),
                ('qr_code_data', models.TextField(blank=True, help_text='Latest QR code in ASCII format', verbose_name='QR Code Data')),
                ('last_connection_time', models.DateTimeField(blank=True, null=True, verbose_name='Last Connected At')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('last_error_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_jid', models.CharField(help_text='WhatsApp group identifier (e.g., 123456789-1234567890@g.us)', max_length=100, unique=True, verbose_name='Group JID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, messages from this group will be ignored', verbose_name='Active (Listen to this group)')),
                ('participant_count', models.IntegerField(default=0, verbose_name='Participant Count')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Group',
                'verbose_name_plural': 'WhatsApp Groups',
                'ordering': ['-last_synced_at', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shipments_w_created_30ad3f_idx')],
            },
        ),
    ]
