# Generated by Django 6.0.1 on 2026-03-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_whatsappconfig_whatsappgroup_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive_api_key_encrypted', models.TextField(blank=True, verbose_name='Motive API Key (Encrypted)')),
                ('motive_base_url', models.URLField(default='https://api.keeptruckin.com/v1', verbose_name='Motive Base URL')),
                ('email_host_user', models.CharField(blank=True, max_length=255, verbose_name='Email Host User')),
                ('email_host_password_encrypted', models.TextField(blank=True, verbose_name='Email Host Password (Encrypted)')),
                ('email_from_email', models.EmailField(blank=True, max_length=254, verbose_name='From Email Address')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
