# Generated by Django 6.0.1 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_invoice_paid_at_invoicelineitem_booking_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('irp', 'IRP'), ('parking', 'PARKING'), ('maintenance', 'Maintenance'), ('truck', 'TRUCK'), ('check_charge', 'CHECK CHARGE'), ('insurance', 'INSURANCE'), ('toll', 'TOLL'), ('fuel', 'FUEL'), ('other', 'OTHER'), ('chassis', 'CHASSIS')], default='other', max_length=20, verbose_name='Category'),
        ),
    ]
