# Generated by Django 6.0.1 on 2026-05-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_alter_expense_category'),
        ('vehicles', '0010_alter_iftamileage_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('irp', 'IRP'), ('parking', 'PARKING'), ('maintenance', 'Maintenance'), ('truck', 'TRUCK'), ('check_charge', 'CHECK CHARGE'), ('insurance', 'INSURANCE'), ('toll', 'TOLL'), ('fuel', 'FUEL'), ('chassis', 'CHASSIS'), ('driver', 'DRIVER'), ('other', 'OTHER')], default='other', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Truck Number'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Truck Numbe'),
        ),
    ]
